#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export HELPDIR='/usr/local/share/zsh/help'

# Customize to your needs...
source ~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh
default_user=cepheus
powerline-daemon -q
